# Generated by Django 2.0.4 on 2018-05-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_customerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='age',
            field=models.SmallIntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
    ]
