# Generated by Django 2.0.4 on 2018-05-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20180528_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('education_table_change', '可以查看kingadmin每张表里所有的数据'), ('education_list_delete', '可以访问kingadmin表里每条数据的修改页'))},
        ),
    ]
