# Generated by Django 2.0.4 on 2018-05-28 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20180528_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('ctime', models.DateField()),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=128, verbose_name='评论')),
                ('ctime', models.DateField()),
                ('aritcle', models.ForeignKey(on_delete=None, to='education.Article')),
                ('reply', models.ForeignKey(null=True, on_delete=None, related_name='back', to='education.Comment', verbose_name='回复评论')),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
        ),
    ]
