# Generated by Django 2.0.4 on 2018-05-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_article_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='back', to='education.Comment', verbose_name='回复评论'),
        ),
    ]
